### ISSUE TITLE
Server Error Error: A required parameter (username) was not provided as a string in getStaticPaths for /[username]/[slug]

### ISSUE THREAD

**Issue by kumarpandule** [fireship-io/next-firebase-course#26]
This error occurred when I imported my firebase database configurations and this shows when I click on any post or when I click on Live view button.
Same Code Without changes.

error - 
Server Error
Error: A required parameter (username) was not provided as a string in getStaticPaths for /[username]/[slug]

This error happened while generating the page. Any console logs will be displayed in the terminal window.
![Screenshot (27)](https://user-images.githubusercontent.com/54455284/201960750-2e60b4f9-9176-4888-988e-90f7e6bf7fab.png)

**Comment by Vilod** [comment]
How did you solve the issue?
